### ISSUE TITLE
Editor.CreateEditor().OnInspectorGUI() doesn't work for the selected _itemInspected.inspectedScript in Chapter 5

### ISSUE THREAD

**Issue by nykevinwong** [angelotadres/RunAndJump#2]
Hi angelotadres,
Your book is really great & amazing and I love it, but I got some issue when I followed the book at safari book site. I was up to chapter 5 with Unity 5.

The below function from chapter 5 is working, but I don't see default inspector of selected _itemInspected.inspectedScript. It always displays C# Scripting instead of public variable of selected inspectedScript.  Is this code not working in Unity 5 any more?

In addition, the code file for each chapter from packet is not a completed project; It is difficult to tell whether the code in the book is incorrect or my own code is incorrect unless I have a full project to run and test for chapter 5.

Tools\LevelCreator\Editor\Levelinspector.cs

```
    private void DrawInspectedItemGUI() {
        // Only show this GUI if we are in edit mode.
        if(_currentMode != Mode.Edit) {
            return; 
        }
        EditorGUILayout.LabelField ("Piece Edited", EditorStyles.boldLabel);
        if(_itemInspected != null) {
            EditorGUILayout.BeginVertical("box");
            EditorGUILayout.LabelField("Name: " + _itemInspected.name);
            Editor.CreateEditor(_itemInspected.inspectedScript).OnInspectorGUI();
            EditorGUILayout.EndVertical();
        } else {
            EditorGUILayout.HelpBox("No piece to edit!", MessageType.Info);
        } 
    }  
```

Thanks,
Kevin

![image](https://cloud.githubusercontent.com/assets/6019725/12161243/997670cc-b4c1-11e5-92d0-aff780d1d674.png)

**Comment by angelotadres** [comment]
Hi Kevin.

First, thanks for buying the book. I'm happy you find this useful :)

All the book's code (the editor related stuff) is on the Packt Pub website (
https://www.packtpub.com/)

There was a mistake when they published the book because they uploaded a
wrong and uncompleted files. This was fixed, so please try again
downloading the code from there.

Let me know if you still with problems.

Regards.

On Thu, Jan 7, 2016 at 12:07 AM, nykevinwong notifications@github.com
wrote:

> Hi angelotadres,
> Your book is really great & amazing and I love it, but I got some issue
> when I followed the book at safari book site I was up to chapter 5 with
> Unity 5
> 
> The below function from chapter 5 is working, but I don't see default
> inspector of selected _itemInspectedinspectedScript It always displays C#
> Scripting instead of public variable of selected inspectedScript Is this
> code not working in Unity 5 any more?
> 
> In addition, the code file for each chapter from packet is not a completed
> project; It is difficult to tell whether the code in the book is incorrect
> or my own code is incorrect unless we have a full project to run and test
> for each chapter
> 
> Tools\LevelCreator\Editor\Levelinspectorcs
> 
> ```
> private void DrawInspectedItemGUI() {
>     // Only show this GUI if we are in edit mode
>     if(_currentMode != ModeEdit) {
>         return;
>     }
>     EditorGUILayoutLabelField ("Piece Edited", EditorStylesboldLabel);
>     if(_itemInspected != null) {
>         EditorGUILayoutBeginVertical("box");
>         EditorGUILayoutLabelField("Name: " + _itemInspectedname);
>         EditorCreateEditor(_itemInspectedinspectedScript)OnInspectorGUI();
>         EditorGUILayoutEndVertical();
>     } else {
>         EditorGUILayoutHelpBox("No piece to edit!", MessageTypeInfo);
>     }
> }
> ```
> 
> Thanks,
> Kevin
> 
> [image: image]
> https://camo.githubusercontent.com/04e7691b36b0820ff3d491fc888b6be97900348b/68747470733a2f2f636c6f756467697468756275736572636f6e74656e74636f6d2f6173736574732f363031393732352f31323136313234332f39393736373063632d623463312d313165352d393264302d616666373830643164363734706e67
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/angelotadres/RunAndJump/issues/2.

## 

_Angelo Tadres_
_Software Engineer_
_University of Chile_

angelotadres.com

**Comment by TheTalisman** [comment]
The problem with the chained call to OnInspectorGUI() is definitely an issue. I'm guessing this may be a bug in Unity?

I encountered this with Unity 5.2.3f1 on Mac and also now with 5.3.1f1 Mac, as well as 5.3.1f1 on Windows.

**Comment by Aerin41** [comment]
Not sure if you've found a fix for this yourself, but I was able to get it working with some tweaks.

In PaletteItem.cs I changed the _inspectedScript_ variable to type LevelPiece instead of type Object. Then in each of the prefabs, I dragged each respective prefab onto the Inspected Script variable in the Inspector. 

I've attached an example for the Interactive Sign. With those changes it all seems to work, hope this helps!

![unitybugfix](https://cloud.githubusercontent.com/assets/9123522/13968835/2a3442f0-f03c-11e5-8103-0f57f7bd0200.jpg)

**Comment by pitsanu** [comment]
@Aerin41  Solved!, thanks.
@angelotadres You should put this to errata.

**Comment by Leucaruth** [comment]
For those who had this problem, the fact is that you dragged a script from the project directly to the object field, this isnt really correct.

If you do it that way, when you instantiate the gameobject from a prefab you wont create a copy of the script that you dragged, its simply a reference to it, thats why you wont be able to create an editor for that script, as it doesnt exist yet.

That's why @Aerin41 it's more or less correct, but you don't need to change the Object type for LevelPiece type, as it negates the abstraction we are trying to put here. You simple have to drag the script that you want to reference, "Interactive Sign Controller" in this case, from the prefab to the Object field. This way it will reference the component that is created when instantiating the gameobject, not just a script.

Notice that if you do it dragging the prefab, it will take the first occurence, from top to down, that matches the requisite of the field, as this is the way Unity works, and maybe you dont want that.

P.S: You can see if you did this well if once dragged the script on the field it says something like "InteractiveSign (InteractiveSignController)" instead just "InteractiveSignController"

**Comment by Aerin41** [comment]
@Leucaruth I'll say that you're right that you don't have to do it the way I mentioned above. Admittedly I was a bit of a newcomer to Unity back in March and didn't realize you could drag the script in the inspector panel directly to a field on another script.

That being said, I still think changing it to type LevelPiece from type Object is better in this case because leaving it as type Object is more prone to error. Leaving it as type Object you're able to put pretty much anything in there and, as we have seen, get an outcome you're not expecting with no obvious cause.

It's true, that in a larger project you might want to have it more abstract to be able to handle more than just LevelPiece types, but there's no need for such abstraction here. If we were all learning in a professional environment, this wouldn't be as big a deal. However, I think it's fair to say that a lot of people who read these books are learning on their own. So it would be prudent to make sure the tutorial has both as little room for error as possible, and making each step explicitly clear.

**Comment by Leucaruth** [comment]
@Aerin41 you are absolutely right in all your statements 👍 

I just wanted to clarify what I thought was happening, as the way it was explained in the book could be a little confusing.

In fact, as you said, people could put the script like that in the inspector because it was an Object type, but it couldn't be dragged there if you transformed it to LevelPiece, because Unity is preventing the behavior I explained this way, and that could be even more confusing to some people.

Cheers ;)

**Comment by Bert-Lemon** [comment]
` Editor ed =CreateEditor(_itemInspected.gameObject.GetComponent(_itemInspected.inspectedScript.name));
  ed.OnInspectorGUI();`

This appears to be working...
